server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Coloufull/cloud.git
          search-paths: config
          username: Coloufull
          password: hl19981213..
      label: master
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
